# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/norazan/R2D2/communication-protocols

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/norazan/R2D2/communication-protocols

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/norazan/R2D2/communication-protocols/CMakeFiles /home/norazan/R2D2/communication-protocols/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/norazan/R2D2/communication-protocols/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rs232

# Build rule for target.
rs232: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rs232
.PHONY : rs232

# fast build rule for target.
rs232/fast:
	$(MAKE) -f CMakeFiles/rs232.dir/build.make CMakeFiles/rs232.dir/build
.PHONY : rs232/fast

#=============================================================================
# Target rules for targets named test_uart

# Build rule for target.
test_uart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_uart
.PHONY : test_uart

# fast build rule for target.
test_uart/fast:
	$(MAKE) -f CMakeFiles/test_uart.dir/build.make CMakeFiles/test_uart.dir/build
.PHONY : test_uart/fast

home/norazan/R2D2/deps/rs232/rs232.o: home/norazan/R2D2/deps/rs232/rs232.c.o
.PHONY : home/norazan/R2D2/deps/rs232/rs232.o

# target to build an object file
home/norazan/R2D2/deps/rs232/rs232.c.o:
	$(MAKE) -f CMakeFiles/rs232.dir/build.make CMakeFiles/rs232.dir/home/norazan/R2D2/deps/rs232/rs232.c.o
.PHONY : home/norazan/R2D2/deps/rs232/rs232.c.o

home/norazan/R2D2/deps/rs232/rs232.i: home/norazan/R2D2/deps/rs232/rs232.c.i
.PHONY : home/norazan/R2D2/deps/rs232/rs232.i

# target to preprocess a source file
home/norazan/R2D2/deps/rs232/rs232.c.i:
	$(MAKE) -f CMakeFiles/rs232.dir/build.make CMakeFiles/rs232.dir/home/norazan/R2D2/deps/rs232/rs232.c.i
.PHONY : home/norazan/R2D2/deps/rs232/rs232.c.i

home/norazan/R2D2/deps/rs232/rs232.s: home/norazan/R2D2/deps/rs232/rs232.c.s
.PHONY : home/norazan/R2D2/deps/rs232/rs232.s

# target to generate assembly for a file
home/norazan/R2D2/deps/rs232/rs232.c.s:
	$(MAKE) -f CMakeFiles/rs232.dir/build.make CMakeFiles/rs232.dir/home/norazan/R2D2/deps/rs232/rs232.c.s
.PHONY : home/norazan/R2D2/deps/rs232/rs232.c.s

source/src/UART.o: source/src/UART.cpp.o
.PHONY : source/src/UART.o

# target to build an object file
source/src/UART.cpp.o:
	$(MAKE) -f CMakeFiles/rs232.dir/build.make CMakeFiles/rs232.dir/source/src/UART.cpp.o
.PHONY : source/src/UART.cpp.o

source/src/UART.i: source/src/UART.cpp.i
.PHONY : source/src/UART.i

# target to preprocess a source file
source/src/UART.cpp.i:
	$(MAKE) -f CMakeFiles/rs232.dir/build.make CMakeFiles/rs232.dir/source/src/UART.cpp.i
.PHONY : source/src/UART.cpp.i

source/src/UART.s: source/src/UART.cpp.s
.PHONY : source/src/UART.s

# target to generate assembly for a file
source/src/UART.cpp.s:
	$(MAKE) -f CMakeFiles/rs232.dir/build.make CMakeFiles/rs232.dir/source/src/UART.cpp.s
.PHONY : source/src/UART.cpp.s

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) -f CMakeFiles/test_uart.dir/build.make CMakeFiles/test_uart.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) -f CMakeFiles/test_uart.dir/build.make CMakeFiles/test_uart.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) -f CMakeFiles/test_uart.dir/build.make CMakeFiles/test_uart.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rs232"
	@echo "... test_uart"
	@echo "... home/norazan/R2D2/deps/rs232/rs232.o"
	@echo "... home/norazan/R2D2/deps/rs232/rs232.i"
	@echo "... home/norazan/R2D2/deps/rs232/rs232.s"
	@echo "... source/src/UART.o"
	@echo "... source/src/UART.i"
	@echo "... source/src/UART.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

